cont = ('Botafogo', 'Palmeiras', 'Internacional', 'Fortaleza', 'Flamengo', 'São Paulo', 'Cruzeiro', 'Bahia', 'Corinthians', 'Atletico-MG', 'Vasco da Gama', 'EC Vitoria', 'Juventude', 'Grêmio', 'Athletico-PR', 'Fluminense', 'Criciúma', 'Bragantino', 'Cuiabá', 'Atlético-GO')
print('-='*50)
print(f'Lista de times do Brasileirão 2024:       {cont}')
print('-='*50)
print(f'Os 5 primeiros são: {cont[0:5]}')
print('-='*50)
print(f'Os 4 últimos colocados: {cont[-4:]}')
print('-='*50)
print(f'TImes em ordem alfabética: {sorted(cont)}')
print('-='*50)
print(f'O São Paulo está na {cont.index('São Paulo')+1} colocação')
print('-='*50)
